### PR TITLE
ENH: Call the DWI plot method from nireports

### PR DESCRIPTION
**Pull request by jhlegarreta**
Call the DWI plot method from its new location in `nireports`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Depends on https://github.com/nipreps/nireports/pull/101 and a new release of `nireports`.

**Review by oesteban — APPROVED** [review]
LGTM - thanks!

**Comment by oesteban** [comment]
Please change from draft to "ready for review" if it is ready.

**Comment by jhlegarreta** [comment]
OK, I see that `nireports` is not pinned, and since a new release was made with this, this is ready to go.

**Pull request merged**
