### PR TITLE
ENH: Add bold realignment notebook (ISMRM'25 Experiment 2)

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by jhlegarreta** [comment]
A few comments:
 - `skimage` and `nipreps` should be added to `pyproject.toml`.
 - Do you think that the plots could be transferred immediately or be useful for `nireports`? If yes, we could transfer them now; if they are useful but not yet ready, we could open an issue there and link to this PR.
 - We need to add the necessary code to retrieve the data and the scripts to preprocess them if applicable (in general for all notebooks).

**Comment by jhlegarreta** [comment]
Related to this PR I believe (found the repo today):
https://github.com/nipreps-data/eddymotion-ismrm25-experiment2

**Comment by jhlegarreta** [comment]
Related to this PR:
https://github.com/nipreps-data/eddymotion-ismrm25-experiment2

**Comment by oesteban** [comment]
Merging so that it starts as part of nifreeze.

**Pull request merged**
