### PR TITLE
ENH: Call the outsourced random volume index iterator in `estimator`

### PR DESCRIPTION
**Pull request by jhlegarreta**
Call the outsourced random volume index iterator in `estimator`.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
I think we will be willing to recover [this](https://github.com/nipreps/eddymotion/pull/150#discussion_r1551850847) in the mid term. For now this PR only avoids duplicate code.

**Review by oesteban — COMMENTED** [review]
> I think we will be willing to recover [this](https://github.com/nipreps/eddymotion/pull/150#discussion_r1551850847) in the mid term. For now this PR only avoids duplicate code.

My idea for this was much less involved, just importing the right iterator (hence the constant interface of all of them). I'm sending a PR against your branch with the suggestion.

**Comment by oesteban** [comment]
Finally. Please check jhlegarreta/eddymotion#4

**Comment by jhlegarreta** [comment]
> Finally. Please check https://github.com/jhlegarreta/eddymotion/pull/4

Nice. Thanks. Merged.

**Review by oesteban — APPROVED** [review]

**Pull request merged**
