### PR TITLE
ENH: Add dMRI covariance model notebook

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add dMRI covariance model notebook.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Depends on PR #123.

Did not figure out how the data points from the HCP data are computed in the original paper figure.

**Comment by jhlegarreta** [comment]
In order to go forward and have the notebook minimal contents available, I'm plotting only the covariance method curves for now. Once this gets merged I'll add the observed covariance data part https://github.com/nipreps/eddymotion/pull/214#issuecomment-2184056027.

**Comment by jhlegarreta** [comment]
@oesteban as discussed this morning, this is ready to be merged. I will add a separate PR once this gets merged to plot the observed covariance from an DWI signal, and will work there to try to solve https://github.com/nipreps/eddymotion/pull/214#issuecomment-2184056027.

**Review by oesteban — APPROVED** [review]
LGTM

**Pull request merged**
